# Alpine Linux as the base image
FROM alpine:3.18

# Labels
LABEL org.opencontainers.image.source=https://github.com/jonbirge/logpager-test
LABEL org.opencontainers.image.description="Web-based log file forensics tool test container"
LABEL org.opencontainers.image.licenses=MIT

# Install nginx, PHP and others
RUN apk update && apk upgrade
RUN apk add --no-cache nginx php82-fpm
RUN apk add --no-cache whois tcptraceroute nmap nmap-scripts

# Install MySQL server
RUN apk add --no-cache mysql mysql-client

# Setup environment variables for localhost MySQL
ENV MYSQL_HOST=localhost
ENV MYSQL_PORT=3306
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root
ENV MYSQL_DATABASE=logpager

# setuid root
RUN chmod u+s /usr/bin/tcptraceroute
RUN chmod u+s /usr/bin/nmap

# Setup Nginx web root
RUN rm -rf /var/www && mkdir -p /var/www && chown -R nginx:nginx /var/www

# Copy Nginx configuration file
COPY default.conf /etc/nginx/http.d/default.conf

# Copy test log files during testing
RUN mkdir -p /var/testlogs
COPY testlogs/* /var/testlogs/
RUN chown -R nginx:nginx /var/testlogs
RUN cp /var/testlogs/* /

# Default /blacklist file and make writable by php-fpm
RUN touch /blacklist && chmod a+w /blacklist

# Startup script
COPY entry.sh /entry.sh

# Copy the source files to the Nginx web root
COPY src/ /var/www/

# Expose standard HTTP port 
EXPOSE 80

# Start nginx and PHP-FPM
CMD ["/entry.sh"]
